table fact_forecasts

	measure 'Forecast Amount' = SUM(fact_forecasts[forecast_amount_eur])
		formatString: #,##0.00

	measure 'Forecast Accuracy' = 1 - ABS(DIVIDE([Actual Amount] - [Forecast Amount], [Forecast Amount], 0))
		formatString: 0.00%

	column forecast_id
		dataType: string
		summarizeBy: none
		sourceColumn: forecast_id

	column fiscal_year
		dataType: int64
		summarizeBy: none
		sourceColumn: fiscal_year

	column period_month
		dataType: int64
		summarizeBy: none
		sourceColumn: period_month

	column period_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: period_date

	column cost_center_id
		dataType: string
		summarizeBy: none
		sourceColumn: cost_center_id

	column account_id
		dataType: string
		summarizeBy: none
		sourceColumn: account_id

	column forecast_amount_eur
		dataType: double
		summarizeBy: sum
		sourceColumn: forecast_amount_eur

	column forecast_type
		dataType: string
		summarizeBy: none
		sourceColumn: forecast_type

	column version
		dataType: string
		summarizeBy: none
		sourceColumn: version

	column created_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: created_date

	partition fact_forecasts_partition = entity
		mode: directLake
		source
			entityName: fact_forecasts
			schemaName: dbo
			expressionSource: DatabaseQuery

